BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEST_CDC PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE TEST_CDC (
    id   NUMBER PRIMARY KEY,
    name VARCHAR2(100)
);

ALTER TABLE TEST_CDC ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
